export const indies = [
    {name:'The Protagonist: EX-1'},
    {name:'SOMOS'},
    {name:'NITE Team 4'},
    {name:'0000'},
    {name:'PLAYCRAFT'},
    {name:'Just Shapes & Beats'},
    {name:'Sneak In'},
    {name:'Hellpoint'},
    {name:'Destination Primus Vita'},
    {name:'King of the Hat'},
    {name:'The Last Aura'},
    {name:'Legends of Ethernal'},
    {name:'The Inner Friend'},
    {name:'Chiaro and the Elixir of Life'}, 
    {name:'Bootleg Systems™'},
    {name:'Eden Rising: Supremacy'},
    {name:'The Grand Block Odyssey'},
    {name:'Cefore'},
    {name:'The Messenger'},
    {name:'FLINTHOOK & MERCENARY KINGS: RELOADED EDITION'},
    {name:'Tiny Derby'},
    {name:'Save Your Nuts'},
    {name:'Feudal Feud'},
    {name:'MageRift'},
    {name:'Trinity'},
    {name:'Spacemen in Space: The Game'},
    {name:'Manoir'},
];